services:
  pg-invoices:
    image: postgres:17-alpine
    ports:
      - '5472:5432'
    environment:
      - POSTGRES_DB=invoices
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    networks:
      - microservices-network

  
  flyway-invoices:
    image: flyway/flyway:10
    container_name: flyway_migrations-invoices
    depends_on:
      - pg-invoices
    volumes:
      - ./Migrations:/flyway/sql
    networks:
      - microservices-network
    command: -url=jdbc:postgresql://pg-invoices:5432/invoices -user=postgres -password=docker -schemas=public migrate

  invoices_api:
    build:
      context: ../.
      dockerfile: Invoices/Dockerfile
    environment:
      - EnviromentVariables__Database__ConnectionString=Host=pg-invoices;Port=5432;Username=postgres;Password=docker;Database=invoices
      - EnviromentVariables__Broker__ConnectionString=amqp://broker:5672
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - pg-invoices
    networks:
      - microservices-network
    ports:
      - "8081:8080"

networks:
  microservices-network:
    driver: bridge
    external: true